name: YiffBukkit
main: de.doridian.yiffbukkit.core.YiffBukkit
version: 1.0.0
depend: [WorldEdit]
softdepend: [dynmap, LogBlock]
commands:
    yb:
        description: Runs any YiffBukkit command (used for console)
        permission: yiffbukkit.no_one_has_this_ever
        usage: /<command>